.TH "C:/Users/Petr/Documents/apo_semestralka/_tech_documentation.md" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/_tech_documentation.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
