.TH "C:/Users/Petr/Documents/apo_semestralka/apoman.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/apoman.c \- Module housing peripherals initialisation, necessary dynamic allocation of memory\&. Creates thread listening to the terminal input\&. Calls run init game menu()\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include 'mzapo_parlcd\&.h'\fP
.br
\fC#include 'mzapo_phys\&.h'\fP
.br
\fC#include 'mzapo_regs\&.h'\fP
.br
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'font_types\&.h'\fP
.br
\fC#include 'map_template\&.h'\fP
.br
\fC#include 'map_from_template\&.h'\fP
.br
\fC#include 'map_to_fb\&.h'\fP
.br
\fC#include 'update_peripherals\&.h'\fP
.br
\fC#include 'text_fb\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include 'game\&.h'\fP
.br
\fC#include 'menu_utilities\&.h'\fP
.br
\fC#include 'terminal_read\&.h'\fP
.br
\fC#include 'pacman\&.h'\fP
.br
\fC#include 'final_score\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_POSIX_C_SOURCE\fP   200112L"
.br
.ti -1c
.RI "#define \fBLED_MAX_VAL\fP   6"
.br
.ti -1c
.RI "#define \fBSCREEN_WIDTH\fP   480"
.br
.ti -1c
.RI "#define \fBSCREEN_HEIGHT\fP   320"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "The main program function\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmtx\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcharacter_has_been_read\fP"
.br
.ti -1c
.RI "\fBread_thread_data_type\fP \fBread_thread_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module housing peripherals initialisation, necessary dynamic allocation of memory\&. Creates thread listening to the terminal input\&. Calls run init game menu()\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz), Petr Kucera (kucerp28@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _POSIX_C_SOURCE   200112L"

.SS "#define LED_MAX_VAL   6"

.SS "#define SCREEN_HEIGHT   320"

.SS "#define SCREEN_WIDTH   480"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
The main program function\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP the count of arguments 
.br
\fIargv\fP program arguments 
.RE
.PP
\fBReturns\fP
.RS 4
int program status 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "pthread_cond_t character_has_been_read"

.SS "pthread_mutex_t mtx"

.SS "\fBread_thread_data_type\fP read_thread_data"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
