.TH "C:/Users/Petr/Documents/apo_semestralka Directory Reference" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapoman\&.c\fP"
.br
.RI "Module housing peripherals initialisation, necessary dynamic allocation of memory\&. Creates thread listening to the terminal input\&. Calls run init game menu()\&. "
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.RI "File, where user preferences can be set\&. For example maximum cap for lives, score gained by eating ghosts/coins can be set here\&. "
.ti -1c
.RI "file \fBdata_structures\&.h\fP"
.br
.RI "File with definitions of data structures used across modules like fb data (data about next frame on the screeen), map data (data about currently played map) "
.ti -1c
.RI "file \fBdraw_shapes\&.c\fP"
.br
.ti -1c
.RI "file \fBdraw_shapes\&.h\fP"
.br
.ti -1c
.RI "file \fBfinal_score\&.c\fP"
.br
.ti -1c
.RI "file \fBfinal_score\&.h\fP"
.br
.ti -1c
.RI "file \fBfont_prop14x16\&.c\fP"
.br
.ti -1c
.RI "file \fBfont_rom8x16\&.c\fP"
.br
.ti -1c
.RI "file \fBfont_types\&.h\fP"
.br
.ti -1c
.RI "file \fBgame\&.c\fP"
.br
.ti -1c
.RI "file \fBgame\&.h\fP"
.br
.ti -1c
.RI "file \fBghost\&.c\fP"
.br
.ti -1c
.RI "file \fBghost\&.h\fP"
.br
.ti -1c
.RI "file \fBmap_circles\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_conch\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_from_template\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_from_template\&.h\fP"
.br
.ti -1c
.RI "file \fBmap_star\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_template\&.h\fP"
.br
.ti -1c
.RI "file \fBmap_to_fb\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_to_fb\&.h\fP"
.br
.ti -1c
.RI "file \fBmenu_utilities\&.c\fP"
.br
.ti -1c
.RI "file \fBmenu_utilities\&.h\fP"
.br
.ti -1c
.RI "file \fBmzapo_parlcd\&.c\fP"
.br
.ti -1c
.RI "file \fBmzapo_parlcd\&.h\fP"
.br
.ti -1c
.RI "file \fBmzapo_phys\&.c\fP"
.br
.ti -1c
.RI "file \fBmzapo_phys\&.h\fP"
.br
.ti -1c
.RI "file \fBmzapo_regs\&.h\fP"
.br
.ti -1c
.RI "file \fBpacman\&.c\fP"
.br
.ti -1c
.RI "file \fBpacman\&.h\fP"
.br
.ti -1c
.RI "file \fBterminal_read\&.c\fP"
.br
.ti -1c
.RI "file \fBterminal_read\&.h\fP"
.br
.ti -1c
.RI "file \fBtext_fb\&.c\fP"
.br
.ti -1c
.RI "file \fBtext_fb\&.h\fP"
.br
.ti -1c
.RI "file \fBupdate_peripherals\&.c\fP"
.br
.ti -1c
.RI "file \fBupdate_peripherals\&.h\fP"
.br
.in -1c
