.TH "C:/Users/Petr/Documents/apo_semestralka/config.h" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/config.h \- File, where user preferences can be set\&. For example maximum cap for lives, score gained by eating ghosts/coins can be set here\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_UP\fP   'w'"
.br
.ti -1c
.RI "#define \fBKEY_DWN\fP   's'"
.br
.ti -1c
.RI "#define \fBKEY_LEFT\fP   'a'"
.br
.ti -1c
.RI "#define \fBKEY_RIGHT\fP   'd'"
.br
.ti -1c
.RI "#define \fBKEY_QUIT\fP   'q'"
.br
.ti -1c
.RI "#define \fBPAUSE_KEY\fP   'p'"
.br
.ti -1c
.RI "#define \fBPAUSE_TEXT\fP   'GAME IS PAUSED'"
.br
.ti -1c
.RI "#define \fBPAUSE_TEXT_SIZE\fP   4"
.br
.ti -1c
.RI "#define \fBPAUSE_SUBTEXT\fP   'press %c to resume or %c to quit'"
.br
.ti -1c
.RI "#define \fBPAUSE_SUBTEXT_SIZE\fP   2"
.br
.ti -1c
.RI "#define \fBPAUSE_SUBTEXT_OFFSET\fP   50"
.br
.ti -1c
.RI "#define \fBPAUSE_FONT\fP   \fBfont_winFreeSystem14x16\fP"
.br
.ti -1c
.RI "#define \fBPAUSE_COLOR\fP   0xffff"
.br
.ti -1c
.RI "#define \fBCOIN_SCORE_INCECREASE\fP   100"
.br
.ti -1c
.RI "#define \fBGHOST_SCORE_INCECREASE\fP   200"
.br
.ti -1c
.RI "#define \fBSCORE_DEATH_PENALTY\fP   0"
.br
.ti -1c
.RI "#define \fBMAX_SCORE\fP   20000"
.br
.ti -1c
.RI "#define \fBMAX_GHOSTS\fP   '4'"
.br
.ti -1c
.RI "#define \fBMAX_LIVES\fP   '4'"
.br
.ti -1c
.RI "#define \fBSCARE_REGIME_DURATION\fP   300"
.br
.ti -1c
.RI "#define \fBGAME_SPEED\fP   2"
.br
.ti -1c
.RI "#define \fBGAME_END_TERMINAL\fP   'Game has ended with pacman getting score %d and having %d lives\\n'"
.br
.ti -1c
.RI "#define \fBLED_SCARE_COLOR1\fP   0"
.br
.ti -1c
.RI "#define \fBLED_SCARE_COLOR2\fP   0xf"
.br
.ti -1c
.RI "#define \fBLED_NORMAL_COLOR\fP   0xf00"
.br
.ti -1c
.RI "#define \fBWALL_COLOR\fP   0x9"
.br
.ti -1c
.RI "#define \fBPATH_COLOR\fP   0"
.br
.ti -1c
.RI "#define \fBCOIN_COLOR\fP   0xd000"
.br
.ti -1c
.RI "#define \fBCOIN_RADIUS\fP   5"
.br
.ti -1c
.RI "#define \fBSUPERCOIN_COLOR\fP   0xf91f"
.br
.ti -1c
.RI "#define \fBSUPERCOIN_RADIUS\fP   5"
.br
.ti -1c
.RI "#define \fBGHOST_COLORS\fP   0x07C0, 0xF01F, 0x07DC, 0xF800"
.br
.ti -1c
.RI "#define \fBGHOST_COLORS_AMMOUNT\fP   4"
.br
.ti -1c
.RI "#define \fBPACMAN_COLOR\fP   0xffe0"
.br
.ti -1c
.RI "#define \fBGHOST_SWITCH_TO_RANDOM\fP   2000"
.br
.ti -1c
.RI "#define \fBGHOST_SWITCH_TO_TARGET\fP   900"
.br
.ti -1c
.RI "#define \fBUP\fP   1"
.br
.ti -1c
.RI "#define \fBRIGHT\fP   2"
.br
.ti -1c
.RI "#define \fBDWN\fP   3"
.br
.ti -1c
.RI "#define \fBLEFT\fP   4"
.br
.in -1c
.SH "Detailed Description"
.PP 
File, where user preferences can be set\&. For example maximum cap for lives, score gained by eating ghosts/coins can be set here\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz), Petr Kucera (kucerp28@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define COIN_COLOR   0xd000"

.SS "#define COIN_RADIUS   5"

.SS "#define COIN_SCORE_INCECREASE   100"

.SS "#define DWN   3"

.SS "#define GAME_END_TERMINAL   'Game has ended with pacman getting score %d and having %d lives\\n'"

.SS "#define GAME_SPEED   2"

.SS "#define GHOST_COLORS   0x07C0, 0xF01F, 0x07DC, 0xF800"

.SS "#define GHOST_COLORS_AMMOUNT   4"

.SS "#define GHOST_SCORE_INCECREASE   200"

.SS "#define GHOST_SWITCH_TO_RANDOM   2000"

.SS "#define GHOST_SWITCH_TO_TARGET   900"

.SS "#define KEY_DWN   's'"

.SS "#define KEY_LEFT   'a'"

.SS "#define KEY_QUIT   'q'"

.SS "#define KEY_RIGHT   'd'"

.SS "#define KEY_UP   'w'"

.SS "#define LED_NORMAL_COLOR   0xf00"

.SS "#define LED_SCARE_COLOR1   0"

.SS "#define LED_SCARE_COLOR2   0xf"

.SS "#define LEFT   4"

.SS "#define MAX_GHOSTS   '4'"

.SS "#define MAX_LIVES   '4'"

.SS "#define MAX_SCORE   20000"

.SS "#define PACMAN_COLOR   0xffe0"

.SS "#define PATH_COLOR   0"

.SS "#define PAUSE_COLOR   0xffff"

.SS "#define PAUSE_FONT   \fBfont_winFreeSystem14x16\fP"

.SS "#define PAUSE_KEY   'p'"

.SS "#define PAUSE_SUBTEXT   'press %c to resume or %c to quit'"

.SS "#define PAUSE_SUBTEXT_OFFSET   50"

.SS "#define PAUSE_SUBTEXT_SIZE   2"

.SS "#define PAUSE_TEXT   'GAME IS PAUSED'"

.SS "#define PAUSE_TEXT_SIZE   4"

.SS "#define RIGHT   2"

.SS "#define SCARE_REGIME_DURATION   300"

.SS "#define SCORE_DEATH_PENALTY   0"

.SS "#define SUPERCOIN_COLOR   0xf91f"

.SS "#define SUPERCOIN_RADIUS   5"

.SS "#define UP   1"

.SS "#define WALL_COLOR   0x9"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
