.TH "coords" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coords
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int x"

.SS "int y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
