.TH "fb_data" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fb_data \- the buffer structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "uint16_t * \fBfb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the buffer structure 
.SH "Field Documentation"
.PP 
.SS "uint16_t* fb"

.SS "int height"

.SS "int width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
