.TH "C:/Users/Petr/Documents/apo_semestralka/final_score.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/final_score.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'font_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBdraw_final_score\fP (int score, \fBfb_data\fP *frame_buff, unsigned char *lcd_mem_base, \fBfont_descriptor_t\fP *font)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool draw_final_score (int score, \fBfb_data\fP * frame_buff, unsigned char * lcd_mem_base, \fBfont_descriptor_t\fP * font)"
function draw final score 
.PP
\fBReturns\fP
.RS 4
false - quit game; true - play game again 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
