.TH "final_score.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
final_score.c \- Module with function draw final score that draws the final score to the screen and waits for user input\&. Returns true if the user pressed the s key and therefor wants to continue playing or the q key indicating he wants to end the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'final_score\&.h'\fP
.br
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include 'update_peripherals\&.h'\fP
.br
\fC#include 'text_fb\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBdraw_final_score\fP (int score, \fBfb_data\fP *frame_buff, unsigned char *lcd_mem_base, \fBfont_descriptor_t\fP *font)"
.br
.RI "Draws the final score to the screen and waits for user input\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module with function draw final score that draws the final score to the screen and waits for user input\&. Returns true if the user pressed the s key and therefor wants to continue playing or the q key indicating he wants to end the program\&. 


.PP
\fBAuthor\fP
.RS 4
Petr Kucera (kucerp28@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool draw_final_score (int score, \fBfb_data\fP * frame_buff, unsigned char * lcd_mem_base, \fBfont_descriptor_t\fP * font)"

.PP
Draws the final score to the screen and waits for user input\&. 
.PP
\fBParameters\fP
.RS 4
\fIscore\fP 
.br
\fIframe_buff\fP 
.br
\fIlcd_mem_base\fP 
.br
\fIfont\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true if the user pressed the s key and therefor wants to continue playing 
.PP
false if the user pressed the q key indicating he wants to end the program 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
