.TH "C:/Users/Petr/Documents/apo_semestralka/font_rom8x16.c" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/font_rom8x16.c
.SH SYNOPSIS
.br
.PP
\fC#include 'font_types\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfont_descriptor_t\fP \fBfont_rom8x16\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBfont_descriptor_t\fP font_rom8x16"
\fBInitial value:\fP
.PP
.nf
= {
    "rom8x16",
    8,
    16,
    12,
    0,
    256,
    rom8x16_bits,
    0,
    0
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
