.TH "font_descriptor_t" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
font_descriptor_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <font_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBmaxwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "int \fBascent\fP"
.br
.ti -1c
.RI "int \fBfirstchar\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "const \fBfont_bits_t\fP * \fBbits\fP"
.br
.ti -1c
.RI "const uint32_t * \fBoffset\fP"
.br
.ti -1c
.RI "const unsigned char * \fBwidth\fP"
.br
.ti -1c
.RI "int \fBdefaultchar\fP"
.br
.ti -1c
.RI "int32_t \fBbits_size\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ascent"

.SS "const \fBfont_bits_t\fP* bits"

.SS "int32_t bits_size"

.SS "int defaultchar"

.SS "int firstchar"

.SS "unsigned int height"

.SS "int maxwidth"

.SS "char* name"

.SS "const uint32_t* offset"

.SS "int size"

.SS "const unsigned char* width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
