.TH "C:/Users/Petr/Documents/apo_semestralka/font_types.h" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/font_types.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfont_descriptor_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint16_t \fBfont_bits_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfont_descriptor_t\fP \fBfont_winFreeSystem14x16\fP"
.br
.ti -1c
.RI "\fBfont_descriptor_t\fP \fBfont_rom8x16\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef uint16_t \fBfont_bits_t\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBfont_descriptor_t\fP font_rom8x16\fC [extern]\fP"

.SS "\fBfont_descriptor_t\fP font_winFreeSystem14x16\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
