.TH "game_init_data_t" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game_init_data_t \- data necessary for game initialization  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpacman_lives\fP"
.br
.ti -1c
.RI "int \fBghost_nr\fP"
.br
.ti -1c
.RI "\fBmap_template\fP * \fBmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
data necessary for game initialization 
.SH "Field Documentation"
.PP 
.SS "int ghost_nr"

.SS "\fBmap_template\fP* map"

.SS "int pacman_lives"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
