.TH "C:/Users/Petr/Documents/apo_semestralka/game.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/game.h
.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'pacman\&.h'\fP
.br
\fC#include 'ghost\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrun_game\fP (\fBgame_init_data_t\fP *game_data, \fBperipherals_data_t\fP *peripherals)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int run_game (\fBgame_init_data_t\fP * game_data, \fBperipherals_data_t\fP * peripherals)"

.PP
\fBReturns\fP
.RS 4
packman score 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
