.TH "C:/Users/Petr/Documents/apo_semestralka/ghost.h" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/ghost.h \- Module where all the logic and movement of ghost is placed\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmoves_costs_t\fP"
.br
.RI "price of movement "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBghost_type\fP \fBcreate_ghost\fP (\fBmap_data\fP *map, int ghost_nr)"
.br
.RI "Creates the ghost at spawning point at map\&. "
.ti -1c
.RI "void \fBdraw_ghost\fP (\fBfb_data\fP *fb, \fBghost_type\fP *ghost, \fBmap_data\fP *map)"
.br
.RI "Draws the ghost to frame buffer with color indicating its state\&. "
.ti -1c
.RI "bool \fBghost_move\fP (\fBghost_type\fP *ghost, \fBmap_data\fP *map, \fBpacman_type\fP *pacman)"
.br
.RI "Has small chance to change the ghost movement from random to targeting and vice versa\&. Changes the ghosts direction if there are more possibilities, moves the ghost in the resulting direction\&. "
.ti -1c
.RI "bool \fBghost_can_move\fP (\fBghost_type\fP *ghost, int dirx, int diry, \fBmap_data\fP *map)"
.br
.RI "Returns true if ghost can move in given direction\&. "
.ti -1c
.RI "int \fBcreate_moves\fP (\fBmoves_costs_t\fP *moves_arr, \fBghost_type\fP *ghost, \fBmap_data\fP *map, \fBpacman_type\fP *pacman)"
.br
.RI "Returns number of possible moves, which it has put into the array along with their cost\&. "
.ti -1c
.RI "void \fBchange_direction\fP (\fBghost_type\fP *ghost, int possibilities, \fBmoves_costs_t\fP *moves_options)"
.br
.RI "Changes the direction of ghost to the path that would lead the closest to pacman or random if ghost is moving randomly\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module where all the logic and movement of ghost is placed\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void change_direction (\fBghost_type\fP * ghost, int possibilities, \fBmoves_costs_t\fP * moves_options)"

.PP
Changes the direction of ghost to the path that would lead the closest to pacman or random if ghost is moving randomly\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP 
.br
\fIpossibilities\fP 
.br
\fImoves_options\fP 
.RE
.PP

.SS "\fBghost_type\fP create_ghost (\fBmap_data\fP * map, int ghost_nr)"

.PP
Creates the ghost at spawning point at map\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP 
.br
\fIghost_nr\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBghost_type\fP 
.RE
.PP

.SS "int create_moves (\fBmoves_costs_t\fP * moves_arr, \fBghost_type\fP * ghost, \fBmap_data\fP * map, \fBpacman_type\fP * pacman)"

.PP
Returns number of possible moves, which it has put into the array along with their cost\&. 
.PP
\fBParameters\fP
.RS 4
\fImoves_arr\fP 
.br
\fIghost\fP 
.br
\fImap\fP 
.br
\fIpacman\fP 
.RE
.PP
\fBReturns\fP
.RS 4
returns number of possible moves, which it has put into the array along with their cost 
.RE
.PP

.SS "void draw_ghost (\fBfb_data\fP * fb, \fBghost_type\fP * ghost, \fBmap_data\fP * map)"

.PP
Draws the ghost to frame buffer with color indicating its state\&. 
.PP
\fBParameters\fP
.RS 4
\fIfb\fP 
.br
\fIghost\fP 
.br
\fImap\fP 
.RE
.PP

.SS "bool ghost_can_move (\fBghost_type\fP * ghost, int dirx, int diry, \fBmap_data\fP * map)"

.PP
Returns true if ghost can move in given direction\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP 
.br
\fIdirx\fP 
.br
\fIdiry\fP 
.br
\fImap\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "bool ghost_move (\fBghost_type\fP * ghost, \fBmap_data\fP * map, \fBpacman_type\fP * pacman)"

.PP
Has small chance to change the ghost movement from random to targeting and vice versa\&. Changes the ghosts direction if there are more possibilities, moves the ghost in the resulting direction\&. 
.PP
\fBParameters\fP
.RS 4
\fIghost\fP 
.br
\fImap\fP 
.br
\fIpacman\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
