.TH "C:/Users/Petr/Documents/apo_semestralka/ghost.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/ghost.h
.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmoves_costs_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBghost_type\fP \fBcreate_ghost\fP (\fBmap_data\fP *map, int ghost_nr)"
.br
.ti -1c
.RI "void \fBdraw_ghost\fP (\fBfb_data\fP *fb, \fBghost_type\fP *ghost, \fBmap_data\fP *map)"
.br
.ti -1c
.RI "bool \fBghost_move\fP (\fBghost_type\fP *ghost, \fBmap_data\fP *map, \fBpacman_type\fP *pacman)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBghost_type\fP create_ghost (\fBmap_data\fP * map, int ghost_nr)"

.SS "void draw_ghost (\fBfb_data\fP * fb, \fBghost_type\fP * ghost, \fBmap_data\fP * map)"

.SS "bool ghost_move (\fBghost_type\fP * ghost, \fBmap_data\fP * map, \fBpacman_type\fP * pacman)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
