.TH "ghost_type" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghost_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBmoving_randomly\fP"
.br
.ti -1c
.RI "bool \fBscared\fP"
.br
.ti -1c
.RI "\fBcoords\fP \fBlocation\fP"
.br
.ti -1c
.RI "\fBcoords\fP \fBdirection\fP"
.br
.ti -1c
.RI "uint16_t \fBcolor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint16_t color"

.SS "\fBcoords\fP direction"

.SS "\fBcoords\fP location"

.SS "bool moving_randomly"

.SS "bool scared"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
