.TH "map_template" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_template \- the definition of the template data structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map_template\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBpacman_spawn_x\fP"
.br
.ti -1c
.RI "int \fBpacman_spawn_y\fP"
.br
.ti -1c
.RI "int \fBghost_spawn_x\fP"
.br
.ti -1c
.RI "int \fBghost_spawn_y\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "char * \fBboard\fP"
.br
.ti -1c
.RI "const int \fBcoin\fP"
.br
.ti -1c
.RI "const int \fBwall\fP"
.br
.ti -1c
.RI "const int \fBspecial\fP"
.br
.ti -1c
.RI "const int \fBblank\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the definition of the template data structure 
.SH "Field Documentation"
.PP 
.SS "const int blank"

.SS "char* board"

.SS "const int coin"

.SS "int ghost_spawn_x"

.SS "int ghost_spawn_y"

.SS "int height"

.SS "char* name"

.SS "int pacman_spawn_x"

.SS "int pacman_spawn_y"

.SS "const int special"

.SS "const int wall"

.SS "int width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
