.TH "C:/Users/Petr/Documents/apo_semestralka/map_to_fb.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/map_to_fb.c \- Module for rendering the map to the frame buffer\&. Houses function render map\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'map_to_fb\&.h'\fP
.br
\fC#include 'map_from_template\&.h'\fP
.br
\fC#include 'text_fb\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBrender_map\fP (\fBmap_data\fP *data, \fBfb_data\fP *frame_buff)"
.br
.RI "given \fBmap_data\fP draws the map to frame buffer "
.in -1c
.SH "Detailed Description"
.PP 
Module for rendering the map to the frame buffer\&. Houses function render map\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool render_map (\fBmap_data\fP * data, \fBfb_data\fP * frame_buff)"

.PP
given \fBmap_data\fP draws the map to frame buffer 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP 
.br
\fIframe_buff\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true if there are any coins to be eaten 
.PP
false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
