.TH "map_data" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_data \- the basic map metadatas  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "char * \fBboard_arr\fP"
.br
.ti -1c
.RI "int \fBmax_object_diameter\fP"
.br
.ti -1c
.RI "\fBcoords\fP \fBghost_spawn\fP"
.br
.ti -1c
.RI "\fBcoords\fP \fBpacman_spawn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the basic map metadatas 
.SH "Field Documentation"
.PP 
.SS "char* board_arr"

.SS "\fBcoords\fP ghost_spawn"

.SS "int height"

.SS "int max_object_diameter"

.SS "\fBcoords\fP pacman_spawn"

.SS "int width"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
