.TH "C:/Users/Petr/Documents/apo_semestralka/map_to_fb.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/map_to_fb.h
.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAT_TO_FB_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBrender_map\fP (\fBmap_data\fP *data, \fBfb_data\fP *frame_buff)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAT_TO_FB_H"

.SH "Function Documentation"
.PP 
.SS "bool render_map (\fBmap_data\fP * data, \fBfb_data\fP * frame_buff)"
given \fBmap_data\fP draws the map to frame buffer, 
.PP
\fBReturns\fP
.RS 4
true if there are any coins to be eaten 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
