.TH "map_star.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_star.c
.SH SYNOPSIS
.br
.PP
\fC#include 'map_template\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmap_template\fP \fBmap_star\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmap_template\fP map_star"
\fBInitial value:\fP
.PP
.nf
= {
    \&.name = "Star_map",
    \&.pacman_spawn_x = 1, 
    \&.pacman_spawn_y = 9, 
    \&.ghost_spawn_x = 13,  
    \&.ghost_spawn_y = 9,  
    \&.width = 15,         
    \&.height = 11,        
    \&.board = board_data_s, 
    \&.coin = 2,           
    \&.wall = 1,           
    \&.special = 3,        
    \&.blank = 0,          
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
