.TH "C:/Users/Petr/Documents/apo_semestralka/map_from_template.h" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/map_from_template.h
.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'map_template\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmap_data\fP * \fBcreate_map_data\fP (int screen_w, int screen_h, \fBmap_template\fP *template)"
.br
.RI "Returns dynamically allocated memory with the data created from the map template given\&. "
.ti -1c
.RI "\fBcoords\fP \fBget_coords_from_template\fP (int row, int col, \fBmap_template\fP *template, int screen_w, int screen_h)"
.br
.RI "Returns coords in the map given coords in the template\&. "
.ti -1c
.RI "void \fBcreate_cell\fP (int row, int col, \fBmap_template\fP *template, \fBmap_data\fP *map)"
.br
.RI "Create a cell (only internal function) "
.ti -1c
.RI "void \fBcreate_cross\fP (int row, int col, \fBmap_template\fP *template, \fBmap_data\fP *map, char center_val)"
.br
.RI "Create a cross (only internal function) "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void create_cell (int row, int col, \fBmap_template\fP * template, \fBmap_data\fP * map)"

.PP
Create a cell (only internal function) 
.PP
\fBParameters\fP
.RS 4
\fIrow\fP 
.br
\fIcol\fP 
.br
\fItemplate\fP 
.br
\fImap\fP 
.RE
.PP

.SS "void create_cross (int row, int col, \fBmap_template\fP * template, \fBmap_data\fP * map, char center_val)"

.PP
Create a cross (only internal function) 
.PP
\fBParameters\fP
.RS 4
\fIrow\fP 
.br
\fIcol\fP 
.br
\fItemplate\fP 
.br
\fImap\fP 
.br
\fIcenter_val\fP 
.RE
.PP

.SS "\fBmap_data\fP* create_map_data (int screen_w, int screen_h, \fBmap_template\fP * template)"

.PP
Returns dynamically allocated memory with the data created from the map template given\&. 
.PP
\fBParameters\fP
.RS 4
\fIscreen_w\fP 
.br
\fIscreen_h\fP 
.br
\fItemplate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
map_data* 
.RE
.PP

.SS "\fBcoords\fP get_coords_from_template (int row, int col, \fBmap_template\fP * template, int screen_w, int screen_h)"

.PP
Returns coords in the map given coords in the template\&. 
.PP
\fBParameters\fP
.RS 4
\fIrow\fP 
.br
\fIcol\fP 
.br
\fItemplate\fP 
.br
\fIscreen_w\fP 
.br
\fIscreen_h\fP 
.RE
.PP
\fBReturns\fP
.RS 4
coords 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
