.TH "C:/Users/Petr/Documents/apo_semestralka/map_template.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/map_template.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmap_template\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmap_template\fP \fBmap_circles\fP"
.br
.ti -1c
.RI "\fBmap_template\fP \fBmap_star\fP"
.br
.ti -1c
.RI "\fBmap_template\fP \fBmap_conch\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmap_template\fP map_circles\fC [extern]\fP"

.SS "\fBmap_template\fP map_conch\fC [extern]\fP"

.SS "\fBmap_template\fP map_star\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
