.TH "C:/Users/Petr/Documents/apo_semestralka/map_to_fb.c" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/map_to_fb.c
.SH SYNOPSIS
.br
.PP
\fC#include 'map_to_fb\&.h'\fP
.br
\fC#include 'map_from_template\&.h'\fP
.br
\fC#include 'text_fb\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBrender_map\fP (\fBmap_data\fP *data, \fBfb_data\fP *frame_buff)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool render_map (\fBmap_data\fP * data, \fBfb_data\fP * frame_buff)"
given \fBmap_data\fP draws the map to frame buffer, 
.PP
\fBReturns\fP
.RS 4
true if there are any coins to be eaten 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
