.TH "md__c___users__petr__documents_apo_semestralka__r_e_a_d_m_e" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users__petr__documents_apo_semestralka__r_e_a_d_m_e \- Semestrální práce na APO 

.SH "Introdukce"
.PP
Cílem této semstrální práce je vytvořit hru Pac-Man, kterou bude možné hrát na desce MzAPO a ovládat pomocí okolních periferií\&.
.PP
Průběh naší práce je možné sledovat v repozitáři: https://gitlab.fel.cvut.cz/kucerp28/apo_semestralka
.SH "Použité periferie a jejich funkce"
.PP
.IP "\(bu" 2
Výstupní řádka led bude při spuštěné hře indikovat počet životů pacmana
.IP "\(bu" 2
RGB led budou svítit zeleně jasem vypočítaným z počtu snězených kostiček, v případě režimu, kdy jsou duchové zranitelní bude blikat modře\&.
.IP "\(bu" 2
Vstupem hry bude terminál v raw režimu, který bude ovládat směr pacmana, respektive navigaci v textovém menu\&.
.IP "\(bu" 2
Po sklonční hry přípravek vypíše finální skóre a statistiky na terminál 
.PP
.SH "Stavy"
.PP
.SS "Inicializace hry"
Po spuštění hry se objeví textové menu, které bude možné ovládat pomocí kláves wsad ze sériového portu\&. Bude zde možnost vybrat mapu z nabídky, nastavit počet duchů a počet životů, se kterými pacman začíná\&.
.SS "Průběh hry"
Samotná hra se bude ovládat pomocí znaků wsad, stejně jako textové menu\&. Pacman pobíhá po desce s cílem sníst co nejvíce 'penízků' a zároveň se nenechat sežrat duchy\&. Pokud sní speciální peníz, spustí se na určitou dobu mód, v kterém bude moci požírat duchy, za což získá další body\&.
.PP
V průběhu hry je možno sledovat mód, ve kterém se hra nachází na tvaru duchů a stavu RGB LED\&. Počet zbývajících životů je indikován na výstupní led řádce jako počet shluků svítících led\&.
.SS "Závěr hry"
Hra může být ukončena 3 způsoby:
.IP "\(bu" 2
Výhrou Pacmana\&. V takovém případě se vypíše skóre hry na terminál a otevře se menu nastavení
.IP "\(bu" 2
Prohrou Pacmana\&. Ta vyvolá stejný proces jako výhra\&.
.IP "\(bu" 2
Přerušením hry pomocí stisknutí klávesy q\&. To hráče odkáže do spouštěcího menu\&.
.PP
.SH "Kompilace"
.PP
.PP
.nf
make TARGET_IP=192\&.168\&.202\&.xx run
.fi
.PP
 
