.TH "md__c___users__petr__documents_apo_semestralka__tech_documentation" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users__petr__documents_apo_semestralka__tech_documentation \- Technická dokumnetace 

.SH "Architektura aplikace"
.PP
Soubory programu jsou děleny dle funkčnosti\&. Podrobnjěí informace s popisem jednotlivých souborů, metod, funkcí, struktur, proměných a maker je možné dohledat v dokumentaci v sekci: \fCFiles\fP\&.
.PP
Aplikace je vytvořena pro MicroZed based MZ_APO board designed by Petr Porazil at \fCPiKRON\fP\&.
.PP
Aplikace vychází z šablony \fCmzapo_template\fP\&.
.SH "Blokové schéma algoritmu"
.PP
Blokové schéma popisuje fungování algoritmu hry Pac-Man\&.
.PP
.PP
Obecně si ho můžeme rozdělit do třech částí:
.PP
.IP "1." 4
konfigurace dané hry (Main menu)
.IP "2." 4
hra samotná (Game)
.IP "3." 4
výpis skóre a pauza (Dispaly score, Pause)
.PP
.SH "Popis kompilace a spuštění programu"
.PP

