.TH "moves_costs_t" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moves_costs_t \- price of movement  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ghost\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcoords\fP \fBdir\fP"
.br
.ti -1c
.RI "int \fBcost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
price of movement 
.SH "Field Documentation"
.PP 
.SS "int cost"

.SS "\fBcoords\fP dir"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
