.TH "C:/Users/Petr/Documents/apo_semestralka/mzapo_regs.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/mzapo_regs.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPILED_REG_BASE_PHYS\fP   0x43c40000"
.br
.ti -1c
.RI "#define \fBSPILED_REG_SIZE\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBSPILED_REG_LED_LINE_o\fP   0x004"
.br
.ti -1c
.RI "#define \fBSPILED_REG_LED_RGB1_o\fP   0x010"
.br
.ti -1c
.RI "#define \fBSPILED_REG_LED_RGB2_o\fP   0x014"
.br
.ti -1c
.RI "#define \fBSPILED_REG_LED_KBDWR_DIRECT_o\fP   0x018"
.br
.ti -1c
.RI "#define \fBSPILED_REG_KBDRD_KNOBS_DIRECT_o\fP   0x020"
.br
.ti -1c
.RI "#define \fBSPILED_REG_KNOBS_8BIT_o\fP   0x024"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_BASE_PHYS\fP   0x43c00000"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_SIZE\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_CR_o\fP   0x0000"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_CR_RESET_m\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_CMD_o\fP   0x0008"
.br
.ti -1c
.RI "#define \fBPARLCD_REG_DATA_o\fP   0x000C"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_BASE_PHYS\fP   0x43c50000"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_SIZE\fP   0x4000"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_CR_o\fP   0x0000"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_PWMPER_o\fP   0x000C"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_PWM1_o\fP   0x0010"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_PWM2_o\fP   0x0014"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_PWM3_o\fP   0x0018"
.br
.ti -1c
.RI "#define \fBSERVOPS2_REG_PWM4_o\fP   0x001C"
.br
.ti -1c
.RI "#define \fBAUDIOPWM_REG_BASE_PHYS\fP   0x43c60000"
.br
.ti -1c
.RI "#define \fBAUDIOPWM_REG_SIZE\fP   0x4000"
.br
.ti -1c
.RI "#define \fBAUDIOPWM_REG_CR_o\fP   0x0000"
.br
.ti -1c
.RI "#define \fBAUDIOPWM_REG_PWMPER_o\fP   0x0008"
.br
.ti -1c
.RI "#define \fBAUDIOPWM_REG_PWM_o\fP   0x000C"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_BASE_PHYS_0\fP   0x43c20000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_BASE_PHYS_1\fP   0x43c30000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_SIZE\fP   0x4000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_CR_o\fP   0x0000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_CR_PWM_A_DIRECT_m\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_CR_PWM_B_DIRECT_m\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_CR_PWM_ENABLE_m\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_CR_IRC_RESET_m\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_SR_o\fP   0x0004"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_SR_IRC_A_MON_m\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_SR_IRC_B_MON_m\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_SR_IRC_IRQ_MON_m\fP   0x00000400"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_PERIOD_o\fP   0x0008"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_PERIOD_MASK_m\fP   0x3fffffff"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_DUTY_o\fP   0x000C"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_DUTY_MASK_m\fP   0x3fffffff"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_DUTY_DIR_A_m\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_DUTY_DIR_B_m\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBDCSPDRV_REG_IRC_o\fP   0x0010"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUDIOPWM_REG_BASE_PHYS   0x43c60000"

.SS "#define AUDIOPWM_REG_CR_o   0x0000"

.SS "#define AUDIOPWM_REG_PWM_o   0x000C"

.SS "#define AUDIOPWM_REG_PWMPER_o   0x0008"

.SS "#define AUDIOPWM_REG_SIZE   0x4000"

.SS "#define DCSPDRV_REG_BASE_PHYS_0   0x43c20000"

.SS "#define DCSPDRV_REG_BASE_PHYS_1   0x43c30000"

.SS "#define DCSPDRV_REG_CR_IRC_RESET_m   0x00000100"

.SS "#define DCSPDRV_REG_CR_o   0x0000"

.SS "#define DCSPDRV_REG_CR_PWM_A_DIRECT_m   0x00000010"

.SS "#define DCSPDRV_REG_CR_PWM_B_DIRECT_m   0x00000020"

.SS "#define DCSPDRV_REG_CR_PWM_ENABLE_m   0x00000040"

.SS "#define DCSPDRV_REG_DUTY_DIR_A_m   0x40000000"

.SS "#define DCSPDRV_REG_DUTY_DIR_B_m   0x80000000"

.SS "#define DCSPDRV_REG_DUTY_MASK_m   0x3fffffff"

.SS "#define DCSPDRV_REG_DUTY_o   0x000C"

.SS "#define DCSPDRV_REG_IRC_o   0x0010"

.SS "#define DCSPDRV_REG_PERIOD_MASK_m   0x3fffffff"

.SS "#define DCSPDRV_REG_PERIOD_o   0x0008"

.SS "#define DCSPDRV_REG_SIZE   0x4000"

.SS "#define DCSPDRV_REG_SR_IRC_A_MON_m   0x00000100"

.SS "#define DCSPDRV_REG_SR_IRC_B_MON_m   0x00000200"

.SS "#define DCSPDRV_REG_SR_IRC_IRQ_MON_m   0x00000400"

.SS "#define DCSPDRV_REG_SR_o   0x0004"

.SS "#define PARLCD_REG_BASE_PHYS   0x43c00000"

.SS "#define PARLCD_REG_CMD_o   0x0008"

.SS "#define PARLCD_REG_CR_o   0x0000"

.SS "#define PARLCD_REG_CR_RESET_m   0x00000002"

.SS "#define PARLCD_REG_DATA_o   0x000C"

.SS "#define PARLCD_REG_SIZE   0x00004000"

.SS "#define SERVOPS2_REG_BASE_PHYS   0x43c50000"

.SS "#define SERVOPS2_REG_CR_o   0x0000"

.SS "#define SERVOPS2_REG_PWM1_o   0x0010"

.SS "#define SERVOPS2_REG_PWM2_o   0x0014"

.SS "#define SERVOPS2_REG_PWM3_o   0x0018"

.SS "#define SERVOPS2_REG_PWM4_o   0x001C"

.SS "#define SERVOPS2_REG_PWMPER_o   0x000C"

.SS "#define SERVOPS2_REG_SIZE   0x4000"

.SS "#define SPILED_REG_BASE_PHYS   0x43c40000"

.SS "#define SPILED_REG_KBDRD_KNOBS_DIRECT_o   0x020"

.SS "#define SPILED_REG_KNOBS_8BIT_o   0x024"

.SS "#define SPILED_REG_LED_KBDWR_DIRECT_o   0x018"

.SS "#define SPILED_REG_LED_LINE_o   0x004"

.SS "#define SPILED_REG_LED_RGB1_o   0x010"

.SS "#define SPILED_REG_LED_RGB2_o   0x014"

.SS "#define SPILED_REG_SIZE   0x00004000"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
