.TH "C:/Users/Petr/Documents/apo_semestralka/pacman.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/pacman.h
.SH SYNOPSIS
.br
.PP
\fC#include 'data_structures\&.h'\fP
.br
\fC#include 'map_template\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpacman_type\fP \fBcreate_pacman\fP (\fBmap_data\fP *map, int lives, int score)"
.br
.ti -1c
.RI "bool \fBpacman_move\fP (\fBpacman_type\fP *pacman, \fBmap_data\fP *map)"
.br
.ti -1c
.RI "void \fBdraw_pacman\fP (\fBpacman_type\fP *pacman, \fBfb_data\fP *fb, \fBmap_data\fP *map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBpacman_type\fP create_pacman (\fBmap_data\fP * map, int lives, int score)"

.SS "void draw_pacman (\fBpacman_type\fP * pacman, \fBfb_data\fP * fb, \fBmap_data\fP * map)"

.SS "bool pacman_move (\fBpacman_type\fP * pacman, \fBmap_data\fP * map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
