.TH "C:/Users/Petr/Documents/apo_semestralka/pacman.c" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/pacman.c \- Module for the controls and rendering of pacman\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pacman\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include 'map_from_template\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpacman_type\fP \fBcreate_pacman\fP (\fBmap_data\fP *map, int lives, int score)"
.br
.RI "Returns pacman with initial score and lives at the spawning coords of the map\&. "
.ti -1c
.RI "bool \fBpacman_move\fP (\fBpacman_type\fP *pacman, \fBmap_data\fP *map)"
.br
.RI "Returns pacman with initial score and lives at the spawning coords of the map\&. "
.ti -1c
.RI "bool \fBpacman_can_move\fP (\fBpacman_type\fP *pacman, int dirx, int diry, \fBmap_data\fP *map)"
.br
.RI "returns true if pacman can move in given direction "
.ti -1c
.RI "void \fBdraw_pacman\fP (\fBpacman_type\fP *pacman, \fBfb_data\fP *fb, \fBmap_data\fP *map)"
.br
.RI "draws circle if pacman is not facing any direction or the ”pie” shape to symbolise the heading "
.in -1c
.SH "Detailed Description"
.PP 
Module for the controls and rendering of pacman\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBpacman_type\fP create_pacman (\fBmap_data\fP * map, int lives, int score)"

.PP
Returns pacman with initial score and lives at the spawning coords of the map\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP 
.br
\fIlives\fP 
.br
\fIscore\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBpacman_type\fP 
.RE
.PP

.SS "void draw_pacman (\fBpacman_type\fP * pacman, \fBfb_data\fP * fb, \fBmap_data\fP * map)"

.PP
draws circle if pacman is not facing any direction or the ”pie” shape to symbolise the heading 
.PP
\fBParameters\fP
.RS 4
\fIpacman\fP 
.br
\fIfb\fP 
.br
\fImap\fP 
.RE
.PP

.SS "bool pacman_can_move (\fBpacman_type\fP * pacman, int dirx, int diry, \fBmap_data\fP * map)"

.PP
returns true if pacman can move in given direction 
.PP
\fBParameters\fP
.RS 4
\fIpacman\fP 
.br
\fIdirx\fP 
.br
\fIdiry\fP 
.br
\fImap\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "bool pacman_move (\fBpacman_type\fP * pacman, \fBmap_data\fP * map)"

.PP
Returns pacman with initial score and lives at the spawning coords of the map\&. 
.PP
\fBParameters\fP
.RS 4
\fIpacman\fP 
.br
\fImap\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
