.TH "pacman_type" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pacman_type \- the pac-man metadatas  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcoords\fP \fBlocation\fP"
.br
.ti -1c
.RI "\fBcoords\fP \fBdirection\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "int \fBlives\fP"
.br
.ti -1c
.RI "int \fBmaxlives\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the pac-man metadatas 
.SH "Field Documentation"
.PP 
.SS "\fBcoords\fP direction"

.SS "int lives"

.SS "\fBcoords\fP location"

.SS "int maxlives"

.SS "int score"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
