.TH "peripherals_data_t" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peripherals_data_t \- peripherals config data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBlcd_mem_base\fP"
.br
.ti -1c
.RI "unsigned char * \fBled_mem_base\fP"
.br
.ti -1c
.RI "int \fBlcd_w\fP"
.br
.ti -1c
.RI "int \fBlcd_h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
peripherals config data 
.SH "Field Documentation"
.PP 
.SS "int lcd_h"

.SS "unsigned char* lcd_mem_base"

.SS "int lcd_w"

.SS "unsigned char* led_mem_base"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
