.TH "read_thread_data_type" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read_thread_data_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBquit\fP"
.br
.ti -1c
.RI "char \fBlast_read\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char last_read"

.SS "bool quit"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
