.TH "C:/Users/Petr/Documents/apo_semestralka/terminal_read.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/terminal_read.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBinput_thread\fP (void *)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* input_thread (void * d)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
