.TH "terminal_read.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminal_read.c \- Module housing the thread function for reading the terminal in nonblocking mode and setting the last key pressed variable\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'terminal_read\&.h'\fP
.br
\fC#include 'data_structures\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <termios\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <poll\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTERMINAL_TIMEOUT_MS\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBinput_thread\fP (void *d)"
.br
.ti -1c
.RI "int \fBserial_getc_timeout\fP (int fd, int timeout_ms, unsigned char *c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module housing the thread function for reading the terminal in nonblocking mode and setting the last key pressed variable\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define TERMINAL_TIMEOUT_MS   100"

.SH "Function Documentation"
.PP 
.SS "void* input_thread (void * d)"

.PP
\fBReturns\fP
.RS 4
void* 
.RE
.PP

.SS "int serial_getc_timeout (int fd, int timeout_ms, unsigned char * c)"

.PP
\fBParameters\fP
.RS 4
\fIfd\fP 
.br
\fItimeout_ms\fP 
.br
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
