.TH "C:/Users/Petr/Documents/apo_semestralka/terminal_read.h" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/terminal_read.h \- Module housing the thread function for reading the terminal in nonblocking mode and setting the last key pressed variable\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBinput_thread\fP (void *)"
.br
.ti -1c
.RI "int \fBserial_getc_timeout\fP (int fd, int timeout_ms, unsigned char *c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module housing the thread function for reading the terminal in nonblocking mode and setting the last key pressed variable\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void* input_thread (void * d)"

.PP
\fBReturns\fP
.RS 4
void* 
.RE
.PP

.SS "int serial_getc_timeout (int fd, int timeout_ms, unsigned char * c)"

.PP
\fBParameters\fP
.RS 4
\fIfd\fP 
.br
\fItimeout_ms\fP 
.br
\fIc\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
