.TH "C:/Users/Petr/Documents/apo_semestralka/text_fb.c" 3 "Tue May 4 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/text_fb.c \- Module for drawing text to frame buffer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'text_fb\&.h'\fP
.br
\fC#include 'draw_shapes\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdraw_char\fP (\fBfb_data\fP *frame, char letter, int x, int y, int scale, \fBfont_descriptor_t\fP *font, uint16_t color)"
.br
.RI "Draws the character to the frame buffer\&. Left upper corner is at x,y and the char is scale times bigger than the bitmap in font\&. "
.ti -1c
.RI "int \fBchar_width\fP (\fBfont_descriptor_t\fP *fdes, int letter)"
.br
.RI "Returns the lenght of given char\&. "
.ti -1c
.RI "uint32_t \fBchar_offset\fP (\fBfont_descriptor_t\fP *fdes, char letter)"
.br
.RI "Returns offset of given char in bitmap data\&. "
.ti -1c
.RI "void \fBdraw_text\fP (\fBfb_data\fP *frame, char *text, int x, int y, int scale, \fBfont_descriptor_t\fP *font, uint16_t color)"
.br
.RI "Draws text to the frame buffer, x,y are the coordinates of the left upper edge\&. "
.ti -1c
.RI "void \fBdraw_text_center\fP (\fBfb_data\fP *frame, char *text, int x, int y, int scale, \fBfont_descriptor_t\fP *font, uint16_t color)"
.br
.RI "Draws the text centered around x,y\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module for drawing text to frame buffer\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "uint32_t char_offset (\fBfont_descriptor_t\fP * fdes, char letter)"

.PP
Returns offset of given char in bitmap data\&. 
.PP
\fBParameters\fP
.RS 4
\fIfdes\fP 
.br
\fIletter\fP 
.RE
.PP
\fBReturns\fP
.RS 4
uint32_t 
.RE
.PP

.SS "int char_width (\fBfont_descriptor_t\fP * fdes, int letter)"

.PP
Returns the lenght of given char\&. 
.PP
\fBParameters\fP
.RS 4
\fIfdes\fP 
.br
\fIletter\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "void draw_char (\fBfb_data\fP * frame, char letter, int x, int y, int scale, \fBfont_descriptor_t\fP * font, uint16_t color)"

.PP
Draws the character to the frame buffer\&. Left upper corner is at x,y and the char is scale times bigger than the bitmap in font\&. 
.PP
\fBParameters\fP
.RS 4
\fIframe\fP 
.br
\fIletter\fP 
.br
\fIx\fP 
.br
\fIy\fP 
.br
\fIscale\fP 
.br
\fIfont\fP 
.br
\fIcolor\fP 
.RE
.PP

.SS "void draw_text (\fBfb_data\fP * frame, char * text, int x, int y, int scale, \fBfont_descriptor_t\fP * font, uint16_t color)"

.PP
Draws text to the frame buffer, x,y are the coordinates of the left upper edge\&. 
.PP
\fBParameters\fP
.RS 4
\fIframe\fP 
.br
\fItext\fP 
.br
\fIx\fP 
.br
\fIy\fP 
.br
\fIscale\fP 
.br
\fIfont\fP 
.br
\fIcolor\fP 
.RE
.PP

.SS "void draw_text_center (\fBfb_data\fP * frame, char * text, int x, int y, int scale, \fBfont_descriptor_t\fP * font, uint16_t color)"

.PP
Draws the text centered around x,y\&. 
.PP
\fBParameters\fP
.RS 4
\fIframe\fP 
.br
\fItext\fP 
.br
\fIx\fP 
.br
\fIy\fP 
.br
\fIscale\fP 
.br
\fIfont\fP 
.br
\fIcolor\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
