.TH "C:/Users/Petr/Documents/apo_semestralka/update_peripherals.c" 3 "Wed May 5 2021" "Version 1.0.0" "Pac-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Petr/Documents/apo_semestralka/update_peripherals.c \- Module for setting the peripherals\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'update_peripherals\&.h'\fP
.br
\fC#include 'mzapo_parlcd\&.h'\fP
.br
\fC#include 'mzapo_regs\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlcd_from_fb\fP (const \fBfb_data\fP *frame_buff, unsigned char *parlcd_mem_base)"
.br
.RI "Sets the lcd pixels to colors described in frame buffer\&. "
.ti -1c
.RI "void \fBled_strip_number\fP (unsigned char *led_mem_base, int max_nr, int nr)"
.br
.RI "Shows number as number of clusters on the led strip\&. "
.ti -1c
.RI "void \fBset_left_RGB\fP (unsigned char *led_mem_base, uint8_t r, uint8_t g, uint8_t b)"
.br
.RI "Sets the left RGB led to particular rgb color\&. "
.ti -1c
.RI "void \fBset_right_RGB\fP (unsigned char *led_mem_base, uint8_t r, uint8_t g, uint8_t b)"
.br
.RI "Sets the right RGB led to particular rgb color\&. "
.ti -1c
.RI "void \fBsel_leds_color\fP (unsigned char *led_mem_base, uint32_t color)"
.br
.RI "Sets both to color\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module for setting the peripherals\&. 


.PP
\fBAuthor\fP
.RS 4
Lukas Nejezchleb (nejezluk@fel.cvut.cz) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-05-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void lcd_from_fb (const \fBfb_data\fP * frame_buff, unsigned char * parlcd_mem_base)"

.PP
Sets the lcd pixels to colors described in frame buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIframe_buff\fP 
.br
\fIparlcd_mem_base\fP 
.RE
.PP

.SS "void led_strip_number (unsigned char * led_mem_base, int max_nr, int nr)"

.PP
Shows number as number of clusters on the led strip\&. 
.PP
\fBParameters\fP
.RS 4
\fIled_mem_base\fP 
.br
\fImax_nr\fP 
.br
\fInr\fP 
.RE
.PP

.SS "void sel_leds_color (unsigned char * led_mem_base, uint32_t color)"

.PP
Sets both to color\&. 
.PP
\fBParameters\fP
.RS 4
\fIled_mem_base\fP 
.br
\fIcolor\fP 
.RE
.PP

.SS "void set_left_RGB (unsigned char * led_mem_base, uint8_t r, uint8_t g, uint8_t b)"

.PP
Sets the left RGB led to particular rgb color\&. 
.PP
\fBParameters\fP
.RS 4
\fIled_mem_base\fP 
.br
\fIr\fP 
.br
\fIg\fP 
.br
\fIb\fP 
.RE
.PP

.SS "void set_right_RGB (unsigned char * led_mem_base, uint8_t r, uint8_t g, uint8_t b)"

.PP
Sets the right RGB led to particular rgb color\&. 
.PP
\fBParameters\fP
.RS 4
\fIled_mem_base\fP 
.br
\fIr\fP 
.br
\fIg\fP 
.br
\fIb\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pac-Man from the source code\&.
